"""User solo email y password

Revision ID: 38d39ce9efac
Revises: 1f1e15c30923
Create Date: 2026-03-05 12:42:48.984287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38d39ce9efac'
down_revision = '1f1e15c30923'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('user')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user', sa.VARCHAR(length=80), nullable=False))

    # ### end Alembic commands ###
