"""Initial_db

Revision ID: 934cc6b00e49
Revises: 
Create Date: 2026-03-04 13:35:09.662879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '934cc6b00e49'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('astillero',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('pais', sa.String(length=50), nullable=True),
    sa.Column('ciudad', sa.String(length=50), nullable=True),
    sa.Column('año_fundacion', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('disenador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('nacionalidad', sa.String(length=50), nullable=True),
    sa.Column('año_nacimiento', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('velero',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('eslora', sa.Float(), nullable=True),
    sa.Column('manga', sa.Float(), nullable=True),
    sa.Column('calado', sa.Float(), nullable=True),
    sa.Column('ano_fabricacion', sa.Integer(), nullable=True),
    sa.Column('astillero_id', sa.Integer(), nullable=True),
    sa.Column('disennador_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['astillero_id'], ['astillero.id'], ),
    sa.ForeignKeyConstraint(['disennador_id'], ['disenador.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('velero')
    op.drop_table('disenador')
    op.drop_table('astillero')
    # ### end Alembic commands ###
